---
commands:
  build_deploy:
    description: "Building project"
    steps:
      - run:
          command: npm run build
          name: Build
      - run:
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
          name: Deploy
  restore_cache_cmd:
    description: "Restore cached npm install"
    steps:
      - restore_cache:
          keys:
            - v1-npm-deps-{{checksum "package.json"}}
            - v1-npm-deps-
  save_cache_cmd:
    description: "Saving npm install"
    steps:
      - save_cache:
          key: v1-npm-deps-{{checksum "package.json"}}
          paths:
            - ./node_modules
  update:
    description: "Installing project's dependencies"
    steps:
      - restore_cache_cmd
      - run:
          command: npm install
          name: "Installing environment"
      - save_cache_cmd
executors:
  docker-executor:
    docker:
      - image: circleci/node:10
jobs:
  build_site:
    executor: docker-executor
    steps:
      - checkout
      - update
      - build_deploy
version: 2.1
workflows:
  build_site:
    jobs:
      - build_site:
          filters:
            branches:
              only: master
