---
commands:
  restore_cache_cmd:
    description: "Restore cached npm install"
    steps:
      - restore_cache:
          key: 'dependency-cache-{{checksum "package.json"}}'
  save_cache_cmd:
    description: "Saving npm install"
    steps:
      - save_cache:
          key: 'dependency-cache-{{ checksum "package.json"}}'
          paths:
            - "./node_modules"
  update:
    description: "Installing project's dependencies"
    steps:
      - checkout
      - restore_cache_cmd
      - run: 
          name: Installing environment
          command: |
            pwd
            npm config get prefix
            sudo npm i -g npm@latest
            sudo npm i
      - save_cache_cmd
  build_deploy:
    description: "Building project"
    steps:
      - checkout
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy
          command: |
            pwd
            ls -la
            chmod -R 755 ~/configstore
            ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" -- only hosting
executors:
  docker-executor:
    docker:
      - image: "cimg/node:12.14.1"
jobs:
  build_site:
    executor: docker-executor
    steps:
      - update
      - build_deploy
version: 2.1
workflows:
  build_site:
    jobs:
      - build_site:
          filters:
            branches:
              only: master
