---
commands:
  restore_cache_cmd:
    description: "Restore cached npm install"
    steps:
      - restore_cache:
          key: 'dependency-cache-{{checksum "package.json"}}'
  save_cache_cmd:
    description: "Saving npm install"
    steps:
      - save_cache:
          key: 'dependency-cache-{{ cachesum "package.json"}}'
          paths:
            - "./node_modules"
  update:
    description: "Building project"
    steps:
      - checkout
      - restore_cache_cmd
      - run: sudo npm i -g npm@latest
      - save_cache_cmd
  deploy:
    description: "Deploying project"
    steps:
      - checkout
      - restore_cache_cmd
      - run: sudo npm run deploy
      - save_cache_cmd
executors:
  docker-executor:
    docker:
      - image: "cimg/node:12.14.1"
jobs:
  deploy_site:
    executor: docker-executor
    steps:
      - update
      - deploy
version: 2.1
workflows:
  build_site:
    jobs:
      - deploy_site
