---
commands:
  build_deploy:
    description: "Building project"
    steps:
      - run:
          command: "npm run build"
          name: Build
      - run:
          command: "./node_modules/.bin/firebase deploy --token \"$FIREBASE_TOKEN\" -- only hosting\n"
          name: Deploy
  restore_cache_cmd:
    description: "Restore cached npm install"
    steps:
      - restore_cache:
          keys:
            - 'dependency-cache-{{checksum "package.json"}}'
            - dependency-cache-
  save_cache_cmd:
    description: "Saving npm install"
    steps:
      - save_cache:
          keys:
            - 'dependency-cache-{{checksum "package.json"}}'
          paths:
            - node_modules
  update:
    description: "Installing project's dependencies"
    steps:
      - restore_cache_cmd
      - run:
          command: "npm install"
          name: "Installing environment"
      - save_cache_cmd
executors:
  docker-executor:
    docker:
      - image: "node:8.15"
jobs:
  build_site:
    executor: docker-executor
    steps:
      - checkout
      - update
      - build_deploy
version: 2.1
workflows:
  build_site:
    jobs:
      - build_site:
          filters:
            branches:
              only: master
