---
commands:
  restore_cache_cmd:
    description: "Restore cached npm install"
    steps:
      - restore_cache:
          keys:
            - dependency-cache-{{checksum "package.json"}}
            - dependency-cache-
  save_cache_cmd:
    description: "Saving npm install"
    steps:
      - save_cache:
          paths:
            - node_modules
          keys:
            - dependency-cache-{{checksum "package.json"}}
  update:
    description: "Installing project's dependencies"
    steps:
      - restore_cache_cmd
      - run:
          name: Installing environment
          command: npm install
      - save_cache_cmd
  build_deploy:
    description: "Building project"
    steps:
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy
          command: |
            ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" -- only hosting
executors:
  docker-executor:
    docker:
      - image: node:8.15
jobs:
  build_site:
    executor: docker-executor
    steps:
      - checkout
      - update
      - build_deploy
version: 2.1
workflows:
  build_site:
    jobs:
      - build_site:
          filters:
            branches:
              only: master
